# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    schedule:
      interval: "daily"

  # Enable version updates for pip
  - package-ecosystem: "pip"
    # Look for `.txt` and `pyproject.toml` files in the `root` directory
    directory: "/"
    schedule:
      interval: "daily"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
